name: cbj_smart_device_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cbj_smart_device:
    path: ../cbj_smart_device
#    git: https://github.com/guyluz11/cbj_smart_device.git
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  network_tools_flutter: ^1.0.4
  network_tools: ^4.0.2
  path_provider: ^2.1.1
  wakelock_plus: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
