name: cbj_smart_device_flutter
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.5+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cbj_integrations_controller:
    git: https://github.com/CyBear-Jinni/cbj_integrations_controller.git
  cbj_smart_device:
    git: https://github.com/CyBear-Jinni/cbj_smart_device.git
  cupertino_icons: ^1.0.6
  # A high performance, open source, general RPC framework that puts mobile and HTTP/2 first.
  grpc: ^3.2.4
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^4.2.1
  wakelock_plus: ^1.1.3

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
